# Generated by Django 4.1.4 on 2022-12-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='age',
            field=models.IntegerField(),
        ),
    ]
